### ISSUE TITLE
Update gems for OpenStudio 3.9.0 (Standards and possibly Extension gem)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-gems#105]
For Standards update to 
https://github.com/NREL/openstudio-standards/releases/tag/v0.7.0

For Extension Gem currently using 0.8.1. Work with UO team to see if this needs to be updated
https://github.com/NREL/openstudio-extension-gem/releases

**Comment by wenyikuang** [comment]
Closed due to #106
