### ISSUE TITLE
Preserve build artifacts from travis

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-gems#2]
After a successful build we will get out a file named:

```
"openstudio-gems-#{DateTime.now.strftime("%Y%m%d")}.tar.gz"
```
or
```
"openstudio3-gems-#{DateTime.now.strftime("%Y%m%d")}.tar.gz"
```
 as well as `Gemfile.lock`.  I'd like to save these artifacts and post them back to the github commit that triggered the build if possible.  We only want to do this for merges to develop or master.

**Comment by macumber** [comment]
@nllong i will need some pointers on how to do this

**Comment by nllong** [comment]
do you want to store these on s3?

**Comment by tijcolem** [comment]
I added a Jenkins CI job to build and post to s3.  See open [PR](https://github.com/NREL/openstudio-gems/pull/5).  

This will build all branches but only upload so s3 when there is commit to develop or master branch. 

If your good with this I suggest we remove .travis as that is redundant.  I'll keep this issue open until PR is merged.

**Comment by tijcolem** [comment]
closing as pr has been merged. https://github.com/NREL/openstudio-gems/pull/5
