### ISSUE TITLE
Update openstudio-standards to 0.6.3

### ISSUE THREAD

**Issue by ainar** [NREL/openstudio-gems#96]
Hi,

I'm facing issues when running measures in OpenStudio 1.8 (https://github.com/NREL/openstudio-model-articulation-gem/issues/145, https://github.com/NREL/openstudio-standards/issues/1815).

After digging, I found these issues disappeared using the last release of openstudio-standards in CLI (currently 0.6.3).
Can the last version of openstudio-standards be used in this repo?

Otherwise, can a user change the version of openstudio-standards user in the OpenStudio Application (without building the entire software)?

**Comment by jmarrec** [comment]
https://github.com/NREL/openstudio-gems/blob/64c28ea2d58ed5c2c47ac0e5a705edca89cf876c/Gemfile#L67
